version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: |
  $Version = $(Get-Content .\VERSION -Raw)
  Set-Item -Path ENV:PRODUCTVERSION -Value $Version
  "#define BINVERSION $($Version.Replace(".",","))`n#define STRVERSION `"$Version`"" | `
    Out-File `
      -FilePath NativeCodeModule/version.h

platform: Both
build:
  project: StripHeaders.sln
  verbosity: normal
after_build:
  - ps: |
      cd chocolatey-package
      ./stripheaders.ps1
      choco pack output/stripheaders.nuspec
artifacts:
- path: Installer\bin\**\Release\*.msi
  name: msi
- path: chocolatey-package\*.nupkg
  name: nupkg
- path: chocolatey-package\CHECKSUM.txt
  name: checksum
deploy:
  provider: GitHub
  auth_token:
    secure: k8FhXZAeG1KcCv5llCgSN3aO7SFH/u3B+xMggvzMIBlPL0rjvCNK4n62SZw+F/1i
  artifact: msi,nupkg,checksum
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true