version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: Set-Item -Path ENV:PRODUCTVERSION -Value $(Get-Content .\VERSION -Raw)
platform: Both
build:
  project: StripHeaders.sln
  verbosity: normal
after_build:
  - ps: >-
      cd chocolatey-package;
      ./stripheaders.ps1;
      choco pack output/stripheaders.nuspec
artifacts:
- path: Installer\bin\**\Release\*.msi
- path: chocolatey-package\*.nupkg
- path: chocolatey-package\CHECKSUM.txt
deploy:
  provider: GitHub
  auth_token:
    secure: k8FhXZAeG1KcCv5llCgSN3aO7SFH/u3B+xMggvzMIBlPL0rjvCNK4n62SZw+F/1i
  artifact: Installer\bin\**\Release\*.msi, chocolatey-package\*.nupkg, chocolatey-package\CHECKSUM.txt
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true